### PR TITLE
JDF-582 - Create a Intermediate BRMS Quickstart: stateful-ksession

### PR DESCRIPTION
**Pull request by rafabene**

### CODE REVIEW

**Comment by sgilda** [comment]
Very nice! I will add a few minor comments to the files, but this is very cool!

**Comment by sgilda** [comment]
I ran into a problem running the Maven tests:

Results :

Tests in error: 
  org.jboss.quickstarts.brms.sfksession.HouseFireTest: Cannot deploy: test.war

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] JBoss BRMS Quickstart: stateful-ksession .......... SUCCESS [0.165s]
[INFO] JBoss BRMS Quickstart: stateful-ksession - kmodule  SUCCESS [3.897s]
[INFO] JBoss BRMS Quickstart: stateful-ksession - web .... FAILURE [15.269s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

 In the surefire reports, it shows:

Caused by: java.lang.Exception: {"JBAS014671: Failed services" => {"jboss.deployment.unit.\"test.war\".WeldStartService" => "org.jboss.msc.service.StartException in service jboss.deployment.unit.\"test.war\".WeldStartService: Failed to start service
    Caused by: org.jboss.weld.exceptions.DeploymentException: WELD-001408 Unsatisfied dependencies for type [KieSession] with qualifiers [@Default] at injection point [[field] @Inject private org.jboss.quickstarts.brms.sfksession.HouseFireTest.kieSession]"}}
    at org.jboss.as.controller.client.helpers.standalone.impl.ServerDeploymentPlanResultFuture.getActionResult(ServerDeploymentPlanResultFuture.java:134)
    at org.jboss.as.controller.client.helpers.standalone.impl.ServerDeploymentPlanResultFuture.getResultFromNode

**Comment by sgilda** [comment]
Very nice job!! Other than the test failure (which is probably something I did wrong), it looks great!

**Comment by rafabene** [comment]
Well, in fact, the test was something that I did wrong :p - I think it's ready now. Thanks for the great feedback

**Comment by sgilda** [comment]
The Arquillian tests now succeed, but I see the following warnings. Do I need to be concerned or are they expected?

Running org.jboss.quickstarts.brms.sfksession.HouseFireTest
Feb 03, 2014 3:02:11 PM org.jboss.shrinkwrap.resolver.impl.maven.logging.LogTransferListener transferFailed
WARNING: Failed downloading org/kie/kie-bom/6.0.1.Final/kie-bom-6.0.1.Final.pom from http://maven.repository.redhat.com/techpreview/all/. Reason: 
org.sonatype.aether.transfer.ArtifactNotFoundException: Could not find artifact org.kie:kie-bom:pom:6.0.1.Final in jboss-ga-repository (http://maven.repository.redhat.com/techpreview/all)
Feb 03, 2014 3:02:11 PM org.jboss.shrinkwrap.resolver.impl.maven.logging.LogTransferListener transferFailed
WARNING: Failed downloading org/kie/kie-bom/6.0.1.Final/kie-bom-6.0.1.Final.pom from http://maven.repository.redhat.com/earlyaccess/all/. Reason: 
org.sonatype.aether.transfer.ArtifactNotFoundException: Could not find artifact org.kie:kie-bom:pom:6.0.1.Final in jboss-earlyaccess-repository (http://maven.repository.redhat.com/earlyaccess/all/)
Feb 03, 2014 3:02:11 PM org.jboss.shrinkwrap.resolver.impl.maven.logging.LogTransferListener transferFailed
WARNING: Failed downloading org/kie/kie-bom/6.0.1.Final/kie-bom-6.0.1.Final.pom from http://jboss-developer.github.io/temp-maven-repo/. Reason: 
org.sonatype.aether.transfer.ArtifactNotFoundException: Could not find artifact org.kie:kie-bom:pom:6.0.1.Final in jboss-developer-repository (http://jboss-developer.github.io/temp-maven-repo/)
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 10.874 sec

**Comment by rafabene** [comment]
That message is somehow expected because Shrinkwrap resolver used on tests (https://github.com/rafabene/jboss-brms-quickstarts/blob/JDF-582/stateful-ksession/web/src/test/java/org/jboss/quickstarts/brms/sfksession/HouseFireTest.java#L63)  tries to find those GAVs on every repo listed on settings.xml. You can ignore them.

**Comment by sgilda** [comment]
We should probably make a note of this in the README file, otherwise, QE will enter  a bug for it. 

In the `store-brms` quickstart, you have a section _Investigate the Console Output_. Maybe that would be useful here along with a note saying the warnings are expected?

**Comment by rafabene** [comment]
I added a commit that shut up SHR warning messages. :)

**Comment by sgilda** [comment]
Now I get failures when I deploy and when I run the tests. I'll start over with a fresh install of the server.

**Comment by rafabene** [comment]
:( ok

**Comment by sgilda** [comment]
It turns out the failure is when I run against the jboss-brms/jboss-eap-6.1/. It works against the plain vanilla jboss-eap-6.2/ release. 

There are duplicates of this line in the README:

```
    Run the Arquillian Tests (For quickstarts that contain Arquillian tests)

    Run the Arquillian Tests
```

 I'll remove it and merge.

**Comment by sgilda** [comment]
Merged.

**Pull request closed without merging**
