### PR TITLE
JDF-585 - Create Advanced BRMS store-brms Quickstart

### PR DESCRIPTION
**Pull request by rafabene**
This is an Advanced Quickstart so probably it will need some BRMS concepts

### CODE REVIEW

**Comment by sgilda** [comment]
I went through the steps and in the Deployment --> Artifact Repository, I see the following JARs:

helloworld-brms-kmodule-6.1.0.jar
org/jboss/quickstarts/brms/helloworld-brms-kmodule/6.1.0/helloworld-brms-kmodule-6.1.0.jar
2014 Feb 3 15:56:38

my-store-brms-kmodule-6.1.0.jar
org/jboss/quickstarts/brms/my-store-brms-kmodule/6.1.0/my-store-brms-kmodule-6.1.0.jar
2014 Feb 3 15:57:23

Then I ran: `mvn clean test -Penable-test`, I get a lot of compilation errors, all related to StoreBRMSTest:

[ERROR] /home/sgilda/GitRepos/jboss-brms-quickstarts/store-brms/src/test/java/org/jboss/quickstarts/brms/StoreBRMSTest.java:[44,19] error: cannot find symbol
[ERROR]  class StoreBRMSTest
/home/sgilda/GitRepos/jboss-brms-quickstarts/store-brms/src/test/java/org/jboss/quickstarts/brms/StoreBRMSTest.java:[46,19] error: cannot find symbol
[ERROR]  class StoreBRMSTest
/home/sgilda/GitRepos/jboss-brms-quickstarts/store-brms/src/test/java/org/jboss/quickstarts/brms/StoreBRMSTest.java:[48,19] error: cannot find symbol
[ERROR]  class StoreBRMSTest
/home/sgilda/GitRepos/jboss-brms-quickstarts/store-brms/src/test/java/org/jboss/quickstarts/brms/StoreBRMSTest.java:[50,19] error: cannot find symbol
[ERROR]  class StoreBRMSTest
/home/sgilda/GitRepos/jboss-brms-quickstarts/store-brms/src/test/java/org/jboss/quickstarts/brms/StoreBRMSTest.java:[53,19] error: cannot find symbol
[ERROR]  class StoreBRMSTest
/home/sgilda/GitRepos/jboss-brms-quickstarts/store-brms/src/test/java/org/jboss/quickstarts/brms/StoreBRMSTest.java:[53,43] error: cannot find symbol

I have that file in my directory:

$ ls -l src/test/java/org/jboss/quickstarts/brms/StoreBRMSTest.java 
-rw-rw-r--. 1 sgilda sgilda 4699 Feb  3 15:23 src/test/java/org/jboss/quickstarts/brms/StoreBRMSTest.java

Any idea what I'm doing wrong?

**Comment by rafabene** [comment]
That's expected. From readme.md: "The tests fail with compilation errors because the project does not have the necessary dependencies."

Now run the following command to run the test goal with the following profiles activated: mvn clean test -Penable-test,brms

**Comment by sgilda** [comment]
Sorry! I was multitasking yesterday and not doing a good job of it.

**Comment by sgilda** [comment]
This looks good to me! I'm not sure if my README comments above are useful or not. Do you want me to merge?

**Comment by rafabene** [comment]
I can merge it if you're too busy.

**Comment by sgilda** [comment]
I'll take care of it :-).

**Comment by sgilda** [comment]
Merged.

**Pull request closed without merging**
