### PR TITLE
JDF-586 Create Intermediate Quickstarts - helloword-cep

### PR DESCRIPTION
**Pull request by rafabene**

### CODE REVIEW

**Comment by sgilda** [comment]
Very nice quickstart. I love the instructions that show you how to test the rules.

I made a few minor changes to the wording in the README file, text that displays in the form, and validation messages and issued a pull back to you. :-)

**Comment by rafabene** [comment]
Thank you so much for the wording changes. It is really much better now. I've added that to this PR and I really also love the possibilities of BRMS/Drools

**Comment by rafabene** [comment]
Merged: https://github.com/jboss-developer/jboss-brms-quickstarts/commit/5c82d1284f223ec93b742d3b13497cd06d77fef6

**Comment by sgilda** [comment]
Merged!

**Pull request closed without merging**
