### PR TITLE
JDF-584 - Create an Intermediate BRMS Quickstart: decision-table

### PR DESCRIPTION
**Pull request by rafabene**

### CODE REVIEW

**Comment by sgilda** [comment]
When I run 

I see a lot of compile errors: `mvn clean test -Penable-test`

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:testCompile (default-testCompile) on project brms-decision-table: Compilation failure: Compilation failure:
[ERROR] /home/sgilda/GitRepos/jboss-brms-quickstarts/decision-table/src/test/java/org/jboss/quickstarts/brms/DecisionTableTest.java:[53,8] error: cannot find symbol
[ERROR] class DecisionTableTest
[ERROR] /home/sgilda/GitRepos/jboss-brms-quickstarts/decision-table/src/test/java/org/jboss/quickstarts/brms/DecisionTableTest.java:[53,44] error: cannot find symbol
[ERROR] class DecisionTableTest
[ERROR] /home/sgilda/GitRepos/jboss-brms-quickstarts/decision-table/src/test/java/org/jboss/quickstarts/brms/DecisionTableTest.java:[59,8] error: cannot find symbol
[ERROR] class DecisionTableTest
[ERROR] /home/sgilda/GitRepos/jboss-brms-quickstarts/decision-table/src/test/java/org/jboss/quickstarts/brms/DecisionTableTest.java:[59,36] error: cannot find symbol
[ERROR] class DecisionTableTest

**Comment by rafabene** [comment]
That's expected. From readme.md: "The tests fail with compilation errors because the project does not have the necessary dependencies."

Now run the following command to run the test goal with the following profiles activated: mvn clean test -Penable-test,brms

**Comment by rafabene** [comment]
The intention on failing is to demonstrate that the dependencies were provided by BRMS. Should I remove this to avoid confusion ?

**Comment by sgilda** [comment]
I wasn't paying attention as well as I should have yesterday. Maybe we could change the wording for the first test run to something like:
1. For these tests, you must add the `brms` dependency on the command line. First try the tests without this dependency. Type the following command to run the test goal with the `enable-test` profile activated:
   
   ```
   mvn clean test -Penable-test
   ```

The tests fail with compilation errors because the project does not have the necessary `brms` dependencies.

**Comment by sgilda** [comment]
I started from scratch and now I'm seeing errors when I run `mvn clean test -Penable-test,brms`.

Tests run: 9, Failures: 0, Errors: 9, Skipped: 0, Time elapsed: 0.768 sec <<< FAILURE!
Results :
Tests in error: 
  testRuleSeniorStatePromotion(org.jboss.quickstarts.brms.DecisionTableTest)
  testRuleStandardJunior(org.jboss.quickstarts.brms.DecisionTableTest)
  testRuleStandardM1Risk(org.jboss.quickstarts.brms.DecisionTableTest)
  testRuleStandardJuniorRisk1(org.jboss.quickstarts.brms.DecisionTableTest)
  testRuleStandardJuniorRisk2(org.jboss.quickstarts.brms.DecisionTableTest)
  testRuleSeniorStatePromotionPlus(org.jboss.quickstarts.brms.DecisionTableTest)
  testRuleStandardYoungLady1(org.jboss.quickstarts.brms.DecisionTableTest)
  testRuleStandardF(org.jboss.quickstarts.brms.DecisionTableTest)
  testRuleStandardM1(org.jboss.quickstarts.brms.DecisionTableTest)

When I choose `Deployment` --> `Artifact Repository`, it displays the following:

Name: my-store-brms-kmodule-6.1.0.jar
Path:  org/jboss/quickstarts/brms/my-store-brms-kmodule/6.1.0/my-store-brms-kmodule-6.1.0.jar
Last Modified: 2014 Feb 4 15:35:17

Name: decision-table-kmodule-6.1.0.jar
Path: org/jboss/quickstarts/brms/decision-table-kmodule/6.1.0/decision-table-kmodule-6.1.0.jar
Last Modified: 2014 Feb 4 15:30:06

So it looks like it deployed both modules. I must have missed a step. I'll start over again.

**Comment by sgilda** [comment]
Merged!

**Pull request closed without merging**
