### PR TITLE
JDF-589 - Create an Beginner BPMS Quickstart: helloworld-bpms

### PR DESCRIPTION
**Pull request by rafabene**

### CODE REVIEW

**Comment by sgilda** [comment]
With BPM, when I try to "Import the BRMS Repository", there is no "Clone Repository" option. I only see "Categories Editor"

**Comment by rafabene** [comment]
You need to select  `Authoring` -> `Administration` first as on step 3. It's there.

**Comment by sgilda** [comment]
I did. I used 'quickstartUser' / 'quickstartPwd1!' and it brought me to that page.
Arghhh! Seems to be there now. Sorry!

**Comment by sgilda** [comment]
Looks good! Should I merge it for you?

**Comment by sgilda** [comment]
@rafabene : I made some minor changes to the root README file and issued a pull back to you:
https://github.com/rafabene/jboss-brms-quickstarts/pull/5

Feel free to use any or none of it!

**Comment by rafabene** [comment]
I agree with you. Just updated with minor changes

**Comment by sgilda** [comment]
Looks good to me!

**Comment by rafabene** [comment]
Are you ok to merge this ?

**Comment by sgilda** [comment]
Yes! That's what I meant by "Looks good to me!". Would you like me to merge it?

**Comment by rafabene** [comment]
Yes. That's what I meant by "Are you ok to merge this ?" LOL

**Comment by sgilda** [comment]
Squashed and merged.

**Pull request closed without merging**
