### PR TITLE
JDF-590 - Create an Advanced BPMS Quickstart: tasks-bpmsuite

### PR DESCRIPTION
**Pull request by rafabene**

### CODE REVIEW

**Comment by rafabene** [comment]
@sgilda  when you have time, could you review and merge it please ?

**Comment by sgilda** [comment]
Sure thing. I will try to get to it first thing tomorrow.

**Comment by sgilda** [comment]
Looks great! I made a few minor comments in the README and I could not find the menu option `Deployment`--> `Artifact Repository`. I've made the edits here, so If you tell me how to find it, I will update the README and merge.

**Comment by rafabene** [comment]
@sgilda  I've updated the Readme as you suggested on both bpms quickstarts. The path for deployments must be changed from Beta to G.A.

**Pull request merged**
